### ISSUE TITLE
S3 0.6.1 aborts with wrong number of arguments

### ISSUE THREAD

**Issue by mchung** [marcel/aws-s3#1]
Code snippet (a Rake task):
    task :boog => :environment do
      require 'aws/s3'
      include AWS::S3

```
  Base.establish_connection!(
    :access_key_id     => S3[:access_key_id],
    :secret_access_key => S3[:secret_access_key]
  )

  begin
    puts "Checking delete..."
    S3Object.delete("TEST", S3[:bucket])
    puts "...Success"
  rescue S3Exception => e
    p e.message
    puts "Fail: Could not delete"
  end
end
```

stack trace:
    trunk/vendor/gems/aws-s3-0.6.1/lib/aws/s3/extensions.rb:137:in `__method__'
    trunk/vendor/gems/aws-s3-0.6.1/lib/aws/s3/extensions.rb:137:in`expirable_memoize'
    trunk/vendor/gems/aws-s3-0.6.1/lib/aws/s3/extensions.rb:176:in `canonical_string'
    trunk/vendor/gems/aws-s3-0.6.1/lib/aws/s3/authentication.rb:72:in`encoded_canonical'
    trunk/vendor/gems/aws-s3-0.6.1/lib/aws/s3/authentication.rb:94:in `initialize'
    trunk/vendor/gems/aws-s3-0.6.1/lib/aws/s3/connection.rb:130:in`new'
    trunk/vendor/gems/aws-s3-0.6.1/lib/aws/s3/connection.rb:130:in `authenticate!'
    trunk/vendor/gems/aws-s3-0.6.1/lib/aws/s3/connection.rb:34:in`request'

**Comment by marcel** [comment]
Could you show me the result of running 'ruby -v' please? Thanks.

**Comment by marcel** [comment]
Try downloading version 0.6.2. Your problem should be fixed now. Let me know if it isn't. Thanks.

**Comment by mchung** [comment]
ruby 1.8.7 (2008-06-20 patchlevel 22) [i686-darwin9]

0.6.2 fixed it. thanks.
