### ISSUE TITLE
Consider adding additional contributors or transferring ownership

### ISSUE THREAD

**Issue by jeffbyrnes** [marcel/aws-s3#110]
@marcel it seems that either your interest in working, or your ability to work, on this gem has waned to the point where a new release hasn’t been cut since May 29, 2012 (according to Rubygems).

Perhaps others might be interested in taking over this project? With 405 forks, it’s clear there’s interest in improving the gem, and there are plenty of issues open.

At the very least, it would be great to cut a release to get #93, #92, #76, #72, and #80 out in the world.

**Comment by hasMattG** [comment]
+1

**Comment by pelargir** [comment]
+1

**Comment by ogonki-vetochki** [comment]
+1

**Comment by yukas** [comment]
+1

**Comment by skogsmaskin** [comment]
+1

**Comment by rugyoga** [comment]
+100

**Comment by mrgordon** [comment]
+1

**Comment by jeffbyrnes** [comment]
Stale, closing.
