### ISSUE TITLE
aws-s3 license?

### ISSUE THREAD

**Issue by mrgordon** [marcel/aws-s3#114]
Would it be possible to clarify what license this project is under?

**Comment by mrgordon** [comment]
Nevermind found it buried in the Rakefile :+1:

**Comment by Sirfrummel** [comment]
You should close this if it's not an issue anymore

**Comment by mrgordon** [comment]
Well its in a strange place so people keep wasting time looking for it which is less than ideal: https://github.com/marcel/aws-s3/pull/113

I'll let their PR supersede my request though
