### ISSUE TITLE
Connection reset by peer and slow uploads

### ISSUE THREAD

**Issue by alexhanh** [marcel/aws-s3#52]
I have about 100 000 files which I'm migrating to S3. Most of the files are under 1MB.

I'm using the aws-s3 gem with Rails 3.1. The bucket is located on the EU server and this is the contents of initializers/s3.rb

``` ruby
require 'aws/s3'

AWS::S3::DEFAULT_HOST.replace "s3-eu-west-1.amazonaws.com"

AWS::S3::Base.establish_connection!(
   :access_key_id     => '...',
   :secret_access_key => '...'
)
```

The background task responsible for migrating the files simply loops the database rows and uploads the associated files to S3:

``` ruby
for image in Image.unmigrated.limit(20)
  AWS::S3::S3Object.store(image.relative_path, open(image.absolute_path), "thebucket")
  if AWS::S3::Service.response.success?
    image.update_attribute(:s3, true)

    File.delete(image.absolute_path)
  end
end
```

I run this through a rake task and two bad things happen:
- At some point (can be after just a few, or even 500 images) the "Connection reset by peer" error comes
- Sometimes the upload speed becomes really slow (sometimes it recovers, sometimes it gives the above error)

I tried the two fixes suggested here https://forums.aws.amazon.com/message.jspa?messageID=86028 , that is, to change the TCP window scaling as well as changing the above code to use

``` ruby
bytes = nil
File.open(image.absolute_path, "rb") { |f| bytes = f.read }
AWS::S3::S3Object.store(image.relative_path, bytes, "thebucket")
```

However, I still keep getting the same fatal error. Any ideas as what I could try?

**Comment by alexhanh** [comment]
Temporal fix I made:

``` ruby
for image in Image.unmigrated.limit(20)
  begin
    AWS::S3::S3Object.store(image.relative_path, open(image.absolute_path), "thebucket")
  rescue StandardError
    next
  end

  if AWS::S3::Service.response.success?
    image.update_attribute(:s3, true)

    File.delete(image.absolute_path)
  end
end
```

Still would love to hear suggestions!

**Comment by marcel** [comment]
I would have just suggested the work around you have above though with a slightly different but similar work around that rescues the connection reset exception and then reconnects and tries to redo up to N times, maybe with exponential back off. There is similar redo logic down inside the connection class I believe.

I don't know what else you could do from the client side but just reconnect and retry.
